[www]
env[DD_TRACE_RESPONSE_BODY_ENABLED] = $DD_TRACE_RESPONSE_BODY_ENABLED
env[DD_TRACE_RESPONSE_BODY_MAX_SIZE] = $DD_TRACE_RESPONSE_BODY_MAX_SIZE
env[DD_TRACE_RESPONSE_BODY_BLACKLIST_URLS] = $DD_TRACE_RESPONSE_BODY_BLACKLIST_URLS
